#! /bin/sh
set -e

case "$1" in
    configure)
        /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
    ;;

    abort-upgrade|abort-deconfigure|abort-remove)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
    ;;
esac

#DEBHELPER#
